version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/broker"
    schedule:
      interval: "weekly"
    groups:
      go-deps:
        patterns: ["*"]

  - package-ecosystem: "gomod"
    directory: "/githubapp"
    schedule:
      interval: "weekly"
    groups:
      go-deps:
        patterns: ["*"]

  - package-ecosystem: "gomod"
    directory: "/cmd/agc"
    schedule:
      interval: "weekly"
    groups:
      go-deps:
        patterns: ["*"]

  - package-ecosystem: "gomod"
    directory: "/cmd/gmc"
    schedule:
      interval: "weekly"
    groups:
      go-deps:
        patterns: ["*"]

  - package-ecosystem: "gomod"
    directory: "/cmd/proxy"
    schedule:
      interval: "weekly"
    groups:
      go-deps:
        patterns: ["*"]

  - package-ecosystem: "gomod"
    directory: "/cmd/worker"
    schedule:
      interval: "weekly"
    groups:
      go-deps:
        patterns: ["*"]

  - package-ecosystem: "gomod"
    directory: "/cmd/probe"
    schedule:
      interval: "weekly"
    groups:
      go-deps:
        patterns: ["*"]

  - package-ecosystem: "gomod"
    directory: "/tools"
    schedule:
      interval: "weekly"
    groups:
      go-deps:
        patterns: ["*"]

  - package-ecosystem: "gomod"
    directory: "/test/fakegithub"
    schedule:
      interval: "weekly"
    groups:
      go-deps:
        patterns: ["*"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions:
        patterns: ["*"]
