#!/usr/bin/env bash
#
# buildkitd-mirror-config.sh — render a buildkitd registry-mirror config from
# REGISTRY_MIRRORS (Q408 Phase 3), or nothing at all when no mirror is wired.
#
# buildkit is the one image client of the e2e job that takes neither dockerd's
# `registry-mirrors` nor a rewritten ref: the base images it resolves are named
# in the Dockerfile (`gcr.io/distroless/static` for four of the six baked
# images, `golang` and `ghcr.io/actions/actions-runner` for the rest), and its
# fetches are the only ones no `actions/cache` entry and no `kind load` can
# cover (plan §2.5). So it gets its own config file, handed to
# docker/setup-buildx-action, which is what the plan's §3.2 buildkit bullet
# leaves open between a build arg and this.
#
# A build arg would reach only the base images we thought to parameterise; this
# covers every registry in the map for every FROM in the Dockerfile, including
# one added later.
#
# Usage:
#   scripts/e2e/buildkitd-mirror-config.sh <output-path>
#
# Prints the path it wrote, so a caller can pass it straight to the action's
# `buildkitd-config` input, and prints NOTHING when REGISTRY_MIRRORS is unset or empty —
# the hosted lane and a developer's `make e2e`, where the builder must keep
# talking to the upstreams directly. Exit 0 in both cases: no mirror configured
# is a configuration, not a failure.
#
# Environment:
#   REGISTRY_MIRRORS — <upstream>=<mirror> map (scripts/lib/registry-mirror.sh)
set -euo pipefail
shopt -s inherit_errexit

out="${1:-}"
if [[ -z "${out}" ]]; then
	echo "usage: $0 <output-path>" >&2
	exit 2
fi

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
# shellcheck source=scripts/lib/registry-mirror.sh
source "${REPO_ROOT}/scripts/lib/registry-mirror.sh"

mapfile -t hosts < <(mirror_hosts)
if (( ${#hosts[@]} == 0 )); then
	exit 0
fi

{
	echo "# Generated by scripts/e2e/buildkitd-mirror-config.sh from REGISTRY_MIRRORS."
	echo "# Every upstream below is served by an in-cluster pull-through cache"
	echo "# (deploy/registry-mirror), reached over plain HTTP inside the cluster."
	for host in "${hosts[@]}"; do
		mirror="$(mirror_for "${host}")"
		# The upstream entry redirects resolution; the mirror's own entry is what
		# permits plain HTTP to it. Without the second block buildkit dials the
		# mirror over TLS, gets a protocol error, and silently falls back to the
		# upstream — a green build that never rode the mirror, which is exactly
		# the reading Phase 3's hit counts have to be able to fail.
		#
		# `http` goes on the MIRROR's entry, not the upstream's, though
		# buildkitd.toml.md's example shows the latter: the resolver builds the
		# mirror host with `fillInsecureOpts(mirrorHost, m[mirrorHost], h)`,
		# keyed on the mirror. Putting it on the upstream would also be a TLS
		# downgrade of the fallback path, which is the opposite of the point.
		echo
		printf '[registry."%s"]\n' "${host}"
		printf '  mirrors = ["%s"]\n' "${mirror}"
		echo
		printf '[registry."%s"]\n' "${mirror}"
		echo '  http = true'
	done
} > "${out}"

printf '%s\n' "${out}"
