---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: agc-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - get
  - update
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - get
  - list
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - watch
- apiGroups:
  - ""
  resources:
  - pods/status
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - resourcequotas
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
- apiGroups:
  - actions-gateway.com
  resources:
  - actionsgateways
  - clusterrunnertemplates
  - egressproxies
  - runnertemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - actions-gateway.com
  resources:
  - runnersets
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - actions-gateway.com
  resources:
  - runnersets/finalizers
  - runnersets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - actions-gateway.github.com
  resources:
  - runnergroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - actions-gateway.github.com
  resources:
  - runnergroups/finalizers
  verbs:
  - update
- apiGroups:
  - actions-gateway.github.com
  resources:
  - runnergroups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - metrics.k8s.io
  resources:
  - pods
  verbs:
  - get
  - list
- apiGroups:
  - node.k8s.io
  resources:
  - runtimeclasses
  verbs:
  - get
  - list
  - watch
