//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PriorityTier) DeepCopyInto(out *PriorityTier) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PriorityTier.
func (in *PriorityTier) DeepCopy() *PriorityTier {
	if in == nil {
		return nil
	}
	out := new(PriorityTier)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunnerGroup) DeepCopyInto(out *RunnerGroup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunnerGroup.
func (in *RunnerGroup) DeepCopy() *RunnerGroup {
	if in == nil {
		return nil
	}
	out := new(RunnerGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RunnerGroup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunnerGroupList) DeepCopyInto(out *RunnerGroupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RunnerGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunnerGroupList.
func (in *RunnerGroupList) DeepCopy() *RunnerGroupList {
	if in == nil {
		return nil
	}
	out := new(RunnerGroupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RunnerGroupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunnerGroupSpec) DeepCopyInto(out *RunnerGroupSpec) {
	*out = *in
	if in.MaxWorkers != nil {
		in, out := &in.MaxWorkers, &out.MaxWorkers
		*out = new(int32)
		**out = **in
	}
	if in.RunnerLabels != nil {
		in, out := &in.RunnerLabels, &out.RunnerLabels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PriorityTiers != nil {
		in, out := &in.PriorityTiers, &out.PriorityTiers
		*out = make([]PriorityTier, len(*in))
		copy(*out, *in)
	}
	in.PodTemplate.DeepCopyInto(&out.PodTemplate)
	if in.MaxEvictionRetries != nil {
		in, out := &in.MaxEvictionRetries, &out.MaxEvictionRetries
		*out = new(int32)
		**out = **in
	}
	if in.EvictionRetryDelay != nil {
		in, out := &in.EvictionRetryDelay, &out.EvictionRetryDelay
		*out = new(v1.Duration)
		**out = **in
	}
	if in.MaxQuotaRetries != nil {
		in, out := &in.MaxQuotaRetries, &out.MaxQuotaRetries
		*out = new(int32)
		**out = **in
	}
	if in.QuotaRetryDelay != nil {
		in, out := &in.QuotaRetryDelay, &out.QuotaRetryDelay
		*out = new(v1.Duration)
		**out = **in
	}
	if in.CompletedPodTTL != nil {
		in, out := &in.CompletedPodTTL, &out.CompletedPodTTL
		*out = new(v1.Duration)
		**out = **in
	}
	if in.PendingPodDeadline != nil {
		in, out := &in.PendingPodDeadline, &out.PendingPodDeadline
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunnerGroupSpec.
func (in *RunnerGroupSpec) DeepCopy() *RunnerGroupSpec {
	if in == nil {
		return nil
	}
	out := new(RunnerGroupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunnerGroupStatus) DeepCopyInto(out *RunnerGroupStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunnerGroupStatus.
func (in *RunnerGroupStatus) DeepCopy() *RunnerGroupStatus {
	if in == nil {
		return nil
	}
	out := new(RunnerGroupStatus)
	in.DeepCopyInto(out)
	return out
}
