//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func (in *RunnerGroup) DeepCopyInto(out *RunnerGroup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *RunnerGroup) DeepCopy() *RunnerGroup {
	if in == nil {
		return nil
	}
	out := new(RunnerGroup)
	in.DeepCopyInto(out)
	return out
}

func (in *RunnerGroup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *RunnerGroupList) DeepCopyInto(out *RunnerGroupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RunnerGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *RunnerGroupList) DeepCopy() *RunnerGroupList {
	if in == nil {
		return nil
	}
	out := new(RunnerGroupList)
	in.DeepCopyInto(out)
	return out
}

func (in *RunnerGroupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *RunnerGroupSpec) DeepCopyInto(out *RunnerGroupSpec) {
	*out = *in
	if in.MaxWorkers != nil {
		x := *in.MaxWorkers
		out.MaxWorkers = &x
	}
	if in.RunnerLabels != nil {
		in, out := &in.RunnerLabels, &out.RunnerLabels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PriorityTiers != nil {
		in, out := &in.PriorityTiers, &out.PriorityTiers
		*out = make([]PriorityTier, len(*in))
		copy(*out, *in)
	}
	in.PodTemplate.DeepCopyInto(&out.PodTemplate)
}

func (in *RunnerGroupSpec) DeepCopy() *RunnerGroupSpec {
	if in == nil {
		return nil
	}
	out := new(RunnerGroupSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *RunnerGroupStatus) DeepCopyInto(out *RunnerGroupStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *RunnerGroupStatus) DeepCopy() *RunnerGroupStatus {
	if in == nil {
		return nil
	}
	out := new(RunnerGroupStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *PriorityTier) DeepCopyInto(out *PriorityTier) {
	*out = *in
}

func (in *PriorityTier) DeepCopy() *PriorityTier {
	if in == nil {
		return nil
	}
	out := new(PriorityTier)
	in.DeepCopyInto(out)
	return out
}
