# This rule is not used by the project gmc itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to actions-gateway.github.com.actions-gateway.github.com resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: gmc
    app.kubernetes.io/managed-by: kustomize
  name: actionsgateway-viewer-role
rules:
- apiGroups:
  - actions-gateway.github.com.actions-gateway.github.com
  resources:
  - actionsgateways
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - actions-gateway.github.com.actions-gateway.github.com
  resources:
  - actionsgateways/status
  verbs:
  - get
