//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v2beta1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AGCVerticalAutoscaling) DeepCopyInto(out *AGCVerticalAutoscaling) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AGCVerticalAutoscaling.
func (in *AGCVerticalAutoscaling) DeepCopy() *AGCVerticalAutoscaling {
	if in == nil {
		return nil
	}
	out := new(AGCVerticalAutoscaling)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActionsGateway) DeepCopyInto(out *ActionsGateway) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActionsGateway.
func (in *ActionsGateway) DeepCopy() *ActionsGateway {
	if in == nil {
		return nil
	}
	out := new(ActionsGateway)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ActionsGateway) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActionsGatewayList) DeepCopyInto(out *ActionsGatewayList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ActionsGateway, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActionsGatewayList.
func (in *ActionsGatewayList) DeepCopy() *ActionsGatewayList {
	if in == nil {
		return nil
	}
	out := new(ActionsGatewayList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ActionsGatewayList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActionsGatewaySpec) DeepCopyInto(out *ActionsGatewaySpec) {
	*out = *in
	in.Credentials.DeepCopyInto(&out.Credentials)
	if in.GitHubCABundleRef != nil {
		in, out := &in.GitHubCABundleRef, &out.GitHubCABundleRef
		*out = new(LocalConfigMapReference)
		**out = **in
	}
	if in.DefaultProxyRef != nil {
		in, out := &in.DefaultProxyRef, &out.DefaultProxyRef
		*out = new(ProxyObjectRef)
		**out = **in
	}
	if in.DefaultTemplateRef != nil {
		in, out := &in.DefaultTemplateRef, &out.DefaultTemplateRef
		*out = new(ObjectRef)
		**out = **in
	}
	if in.AGCResources != nil {
		in, out := &in.AGCResources, &out.AGCResources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.AGCAutoscaling != nil {
		in, out := &in.AGCAutoscaling, &out.AGCAutoscaling
		*out = new(AGCVerticalAutoscaling)
		**out = **in
	}
	in.Tracing.DeepCopyInto(&out.Tracing)
	if in.Scheduling != nil {
		in, out := &in.Scheduling, &out.Scheduling
		*out = new(PodScheduling)
		(*in).DeepCopyInto(*out)
	}
	if in.ClusterCapacity != nil {
		in, out := &in.ClusterCapacity, &out.ClusterCapacity
		*out = new(ClusterCapacity)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActionsGatewaySpec.
func (in *ActionsGatewaySpec) DeepCopy() *ActionsGatewaySpec {
	if in == nil {
		return nil
	}
	out := new(ActionsGatewaySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActionsGatewayStatus) DeepCopyInto(out *ActionsGatewayStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActionsGatewayStatus.
func (in *ActionsGatewayStatus) DeepCopy() *ActionsGatewayStatus {
	if in == nil {
		return nil
	}
	out := new(ActionsGatewayStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CapacityGate) DeepCopyInto(out *CapacityGate) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CapacityGate.
func (in *CapacityGate) DeepCopy() *CapacityGate {
	if in == nil {
		return nil
	}
	out := new(CapacityGate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterCapacity) DeepCopyInto(out *ClusterCapacity) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterCapacity.
func (in *ClusterCapacity) DeepCopy() *ClusterCapacity {
	if in == nil {
		return nil
	}
	out := new(ClusterCapacity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterRunnerTemplate) DeepCopyInto(out *ClusterRunnerTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterRunnerTemplate.
func (in *ClusterRunnerTemplate) DeepCopy() *ClusterRunnerTemplate {
	if in == nil {
		return nil
	}
	out := new(ClusterRunnerTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterRunnerTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterRunnerTemplateList) DeepCopyInto(out *ClusterRunnerTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterRunnerTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterRunnerTemplateList.
func (in *ClusterRunnerTemplateList) DeepCopy() *ClusterRunnerTemplateList {
	if in == nil {
		return nil
	}
	out := new(ClusterRunnerTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterRunnerTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerSizingRecommendation) DeepCopyInto(out *ContainerSizingRecommendation) {
	*out = *in
	if in.Requests != nil {
		in, out := &in.Requests, &out.Requests
		*out = make(v1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	if in.Limits != nil {
		in, out := &in.Limits, &out.Limits
		*out = make(v1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	if in.ObservedPeak != nil {
		in, out := &in.ObservedPeak, &out.ObservedPeak
		*out = make(v1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	if in.ObservedP95 != nil {
		in, out := &in.ObservedP95, &out.ObservedP95
		*out = make(v1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	in.WindowStartTime.DeepCopyInto(&out.WindowStartTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerSizingRecommendation.
func (in *ContainerSizingRecommendation) DeepCopy() *ContainerSizingRecommendation {
	if in == nil {
		return nil
	}
	out := new(ContainerSizingRecommendation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EgressPeer) DeepCopyInto(out *EgressPeer) {
	*out = *in
	if in.PodSelector != nil {
		in, out := &in.PodSelector, &out.PodSelector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.NamespaceSelector != nil {
		in, out := &in.NamespaceSelector, &out.NamespaceSelector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EgressPeer.
func (in *EgressPeer) DeepCopy() *EgressPeer {
	if in == nil {
		return nil
	}
	out := new(EgressPeer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EgressProxy) DeepCopyInto(out *EgressProxy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EgressProxy.
func (in *EgressProxy) DeepCopy() *EgressProxy {
	if in == nil {
		return nil
	}
	out := new(EgressProxy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EgressProxy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EgressProxyList) DeepCopyInto(out *EgressProxyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EgressProxy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EgressProxyList.
func (in *EgressProxyList) DeepCopy() *EgressProxyList {
	if in == nil {
		return nil
	}
	out := new(EgressProxyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EgressProxyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EgressProxySpec) DeepCopyInto(out *EgressProxySpec) {
	*out = *in
	if in.MinReplicas != nil {
		in, out := &in.MinReplicas, &out.MinReplicas
		*out = new(int32)
		**out = **in
	}
	if in.MaxReplicas != nil {
		in, out := &in.MaxReplicas, &out.MaxReplicas
		*out = new(int32)
		**out = **in
	}
	if in.TargetCPUUtilizationPercentage != nil {
		in, out := &in.TargetCPUUtilizationPercentage, &out.TargetCPUUtilizationPercentage
		*out = new(int32)
		**out = **in
	}
	if in.ManagedAutoscaling != nil {
		in, out := &in.ManagedAutoscaling, &out.ManagedAutoscaling
		*out = new(bool)
		**out = **in
	}
	in.Resources.DeepCopyInto(&out.Resources)
	if in.NoProxyCIDRs != nil {
		in, out := &in.NoProxyCIDRs, &out.NoProxyCIDRs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ManagedNetworkPolicy != nil {
		in, out := &in.ManagedNetworkPolicy, &out.ManagedNetworkPolicy
		*out = new(bool)
		**out = **in
	}
	if in.DestinationFQDNs != nil {
		in, out := &in.DestinationFQDNs, &out.DestinationFQDNs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DestinationCIDRs != nil {
		in, out := &in.DestinationCIDRs, &out.DestinationCIDRs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Sharing != nil {
		in, out := &in.Sharing, &out.Sharing
		*out = new(ProxySharing)
		(*in).DeepCopyInto(*out)
	}
	if in.Scheduling != nil {
		in, out := &in.Scheduling, &out.Scheduling
		*out = new(PodScheduling)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EgressProxySpec.
func (in *EgressProxySpec) DeepCopy() *EgressProxySpec {
	if in == nil {
		return nil
	}
	out := new(EgressProxySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EgressProxyStatus) DeepCopyInto(out *EgressProxyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EgressProxyStatus.
func (in *EgressProxyStatus) DeepCopy() *EgressProxyStatus {
	if in == nil {
		return nil
	}
	out := new(EgressProxyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalSigner) DeepCopyInto(out *ExternalSigner) {
	*out = *in
	if in.Vault != nil {
		in, out := &in.Vault, &out.Vault
		*out = new(VaultSigner)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalSigner.
func (in *ExternalSigner) DeepCopy() *ExternalSigner {
	if in == nil {
		return nil
	}
	out := new(ExternalSigner)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubCredentials) DeepCopyInto(out *GitHubCredentials) {
	*out = *in
	if in.GitHubApp != nil {
		in, out := &in.GitHubApp, &out.GitHubApp
		*out = new(LocalSecretReference)
		**out = **in
	}
	if in.WorkloadIdentity != nil {
		in, out := &in.WorkloadIdentity, &out.WorkloadIdentity
		*out = new(WorkloadIdentity)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubCredentials.
func (in *GitHubCredentials) DeepCopy() *GitHubCredentials {
	if in == nil {
		return nil
	}
	out := new(GitHubCredentials)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalConfigMapReference) DeepCopyInto(out *LocalConfigMapReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalConfigMapReference.
func (in *LocalConfigMapReference) DeepCopy() *LocalConfigMapReference {
	if in == nil {
		return nil
	}
	out := new(LocalConfigMapReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalSecretReference) DeepCopyInto(out *LocalSecretReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalSecretReference.
func (in *LocalSecretReference) DeepCopy() *LocalSecretReference {
	if in == nil {
		return nil
	}
	out := new(LocalSecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeShareSizing) DeepCopyInto(out *NodeShareSizing) {
	*out = *in
	if in.Allocatable != nil {
		in, out := &in.Allocatable, &out.Allocatable
		*out = make(v1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeShareSizing.
func (in *NodeShareSizing) DeepCopy() *NodeShareSizing {
	if in == nil {
		return nil
	}
	out := new(NodeShareSizing)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectRef) DeepCopyInto(out *ObjectRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectRef.
func (in *ObjectRef) DeepCopy() *ObjectRef {
	if in == nil {
		return nil
	}
	out := new(ObjectRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodScheduling) DeepCopyInto(out *PodScheduling) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(v1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	if in.TopologySpreadConstraints != nil {
		in, out := &in.TopologySpreadConstraints, &out.TopologySpreadConstraints
		*out = make([]v1.TopologySpreadConstraint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodScheduling.
func (in *PodScheduling) DeepCopy() *PodScheduling {
	if in == nil {
		return nil
	}
	out := new(PodScheduling)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PriorityClassAllowlist) DeepCopyInto(out *PriorityClassAllowlist) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PriorityClassAllowlist.
func (in *PriorityClassAllowlist) DeepCopy() *PriorityClassAllowlist {
	if in == nil {
		return nil
	}
	out := new(PriorityClassAllowlist)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PriorityClassAllowlist) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PriorityClassAllowlistList) DeepCopyInto(out *PriorityClassAllowlistList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PriorityClassAllowlist, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PriorityClassAllowlistList.
func (in *PriorityClassAllowlistList) DeepCopy() *PriorityClassAllowlistList {
	if in == nil {
		return nil
	}
	out := new(PriorityClassAllowlistList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PriorityClassAllowlistList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PriorityClassAllowlistSpec) DeepCopyInto(out *PriorityClassAllowlistSpec) {
	*out = *in
	if in.AllowedPriorityClasses != nil {
		in, out := &in.AllowedPriorityClasses, &out.AllowedPriorityClasses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AllowedInfraPriorityClasses != nil {
		in, out := &in.AllowedInfraPriorityClasses, &out.AllowedInfraPriorityClasses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PriorityClassAllowlistSpec.
func (in *PriorityClassAllowlistSpec) DeepCopy() *PriorityClassAllowlistSpec {
	if in == nil {
		return nil
	}
	out := new(PriorityClassAllowlistSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PriorityTier) DeepCopyInto(out *PriorityTier) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PriorityTier.
func (in *PriorityTier) DeepCopy() *PriorityTier {
	if in == nil {
		return nil
	}
	out := new(PriorityTier)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxyObjectRef) DeepCopyInto(out *ProxyObjectRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyObjectRef.
func (in *ProxyObjectRef) DeepCopy() *ProxyObjectRef {
	if in == nil {
		return nil
	}
	out := new(ProxyObjectRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxySharing) DeepCopyInto(out *ProxySharing) {
	*out = *in
	if in.AllowedNamespaces != nil {
		in, out := &in.AllowedNamespaces, &out.AllowedNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxySharing.
func (in *ProxySharing) DeepCopy() *ProxySharing {
	if in == nil {
		return nil
	}
	out := new(ProxySharing)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunnerSet) DeepCopyInto(out *RunnerSet) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunnerSet.
func (in *RunnerSet) DeepCopy() *RunnerSet {
	if in == nil {
		return nil
	}
	out := new(RunnerSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RunnerSet) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunnerSetList) DeepCopyInto(out *RunnerSetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RunnerSet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunnerSetList.
func (in *RunnerSetList) DeepCopy() *RunnerSetList {
	if in == nil {
		return nil
	}
	out := new(RunnerSetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RunnerSetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunnerSetSpec) DeepCopyInto(out *RunnerSetSpec) {
	*out = *in
	out.GatewayRef = in.GatewayRef
	if in.TemplateRef != nil {
		in, out := &in.TemplateRef, &out.TemplateRef
		*out = new(ObjectRef)
		**out = **in
	}
	if in.ProxyRef != nil {
		in, out := &in.ProxyRef, &out.ProxyRef
		*out = new(ProxyObjectRef)
		**out = **in
	}
	if in.MaxWorkers != nil {
		in, out := &in.MaxWorkers, &out.MaxWorkers
		*out = new(int32)
		**out = **in
	}
	if in.RunnerLabels != nil {
		in, out := &in.RunnerLabels, &out.RunnerLabels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PriorityTiers != nil {
		in, out := &in.PriorityTiers, &out.PriorityTiers
		*out = make([]PriorityTier, len(*in))
		copy(*out, *in)
	}
	if in.MaxEvictionRetries != nil {
		in, out := &in.MaxEvictionRetries, &out.MaxEvictionRetries
		*out = new(int32)
		**out = **in
	}
	if in.EvictionRetryDelay != nil {
		in, out := &in.EvictionRetryDelay, &out.EvictionRetryDelay
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.MaxQuotaRetries != nil {
		in, out := &in.MaxQuotaRetries, &out.MaxQuotaRetries
		*out = new(int32)
		**out = **in
	}
	if in.QuotaRetryDelay != nil {
		in, out := &in.QuotaRetryDelay, &out.QuotaRetryDelay
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.CompletedPodTTL != nil {
		in, out := &in.CompletedPodTTL, &out.CompletedPodTTL
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.PendingPodDeadline != nil {
		in, out := &in.PendingPodDeadline, &out.PendingPodDeadline
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.MaxWorkerLifetime != nil {
		in, out := &in.MaxWorkerLifetime, &out.MaxWorkerLifetime
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.ScaleUp != nil {
		in, out := &in.ScaleUp, &out.ScaleUp
		*out = new(ScaleUpRateLimit)
		(*in).DeepCopyInto(*out)
	}
	if in.Sizing != nil {
		in, out := &in.Sizing, &out.Sizing
		*out = new(WorkerSizing)
		(*in).DeepCopyInto(*out)
	}
	if in.CapacityGate != nil {
		in, out := &in.CapacityGate, &out.CapacityGate
		*out = new(CapacityGate)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunnerSetSpec.
func (in *RunnerSetSpec) DeepCopy() *RunnerSetSpec {
	if in == nil {
		return nil
	}
	out := new(RunnerSetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunnerSetStatus) DeepCopyInto(out *RunnerSetStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AdvertisedCapacity != nil {
		in, out := &in.AdvertisedCapacity, &out.AdvertisedCapacity
		*out = new(int32)
		**out = **in
	}
	if in.WithheldCapacity != nil {
		in, out := &in.WithheldCapacity, &out.WithheldCapacity
		*out = make([]WithheldCapacity, len(*in))
		copy(*out, *in)
	}
	if in.SizingRecommendation != nil {
		in, out := &in.SizingRecommendation, &out.SizingRecommendation
		*out = make([]ContainerSizingRecommendation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunnerSetStatus.
func (in *RunnerSetStatus) DeepCopy() *RunnerSetStatus {
	if in == nil {
		return nil
	}
	out := new(RunnerSetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunnerTemplate) DeepCopyInto(out *RunnerTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunnerTemplate.
func (in *RunnerTemplate) DeepCopy() *RunnerTemplate {
	if in == nil {
		return nil
	}
	out := new(RunnerTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RunnerTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunnerTemplateList) DeepCopyInto(out *RunnerTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RunnerTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunnerTemplateList.
func (in *RunnerTemplateList) DeepCopy() *RunnerTemplateList {
	if in == nil {
		return nil
	}
	out := new(RunnerTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RunnerTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunnerTemplateSpec) DeepCopyInto(out *RunnerTemplateSpec) {
	*out = *in
	in.PodTemplate.DeepCopyInto(&out.PodTemplate)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunnerTemplateSpec.
func (in *RunnerTemplateSpec) DeepCopy() *RunnerTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(RunnerTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunnerTemplateStatus) DeepCopyInto(out *RunnerTemplateStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunnerTemplateStatus.
func (in *RunnerTemplateStatus) DeepCopy() *RunnerTemplateStatus {
	if in == nil {
		return nil
	}
	out := new(RunnerTemplateStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScaleUpRateLimit) DeepCopyInto(out *ScaleUpRateLimit) {
	*out = *in
	if in.Burst != nil {
		in, out := &in.Burst, &out.Burst
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScaleUpRateLimit.
func (in *ScaleUpRateLimit) DeepCopy() *ScaleUpRateLimit {
	if in == nil {
		return nil
	}
	out := new(ScaleUpRateLimit)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TracingConfig) DeepCopyInto(out *TracingConfig) {
	*out = *in
	if in.Insecure != nil {
		in, out := &in.Insecure, &out.Insecure
		*out = new(bool)
		**out = **in
	}
	if in.ResourceAttributes != nil {
		in, out := &in.ResourceAttributes, &out.ResourceAttributes
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TracingConfig.
func (in *TracingConfig) DeepCopy() *TracingConfig {
	if in == nil {
		return nil
	}
	out := new(TracingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultKubernetesAuth) DeepCopyInto(out *VaultKubernetesAuth) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultKubernetesAuth.
func (in *VaultKubernetesAuth) DeepCopy() *VaultKubernetesAuth {
	if in == nil {
		return nil
	}
	out := new(VaultKubernetesAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultSigner) DeepCopyInto(out *VaultSigner) {
	*out = *in
	out.Auth = in.Auth
	if in.NetworkPolicy != nil {
		in, out := &in.NetworkPolicy, &out.NetworkPolicy
		*out = new(EgressPeer)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultSigner.
func (in *VaultSigner) DeepCopy() *VaultSigner {
	if in == nil {
		return nil
	}
	out := new(VaultSigner)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WithheldCapacity) DeepCopyInto(out *WithheldCapacity) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WithheldCapacity.
func (in *WithheldCapacity) DeepCopy() *WithheldCapacity {
	if in == nil {
		return nil
	}
	out := new(WithheldCapacity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkerSizing) DeepCopyInto(out *WorkerSizing) {
	*out = *in
	if in.LimitHeadroomPercent != nil {
		in, out := &in.LimitHeadroomPercent, &out.LimitHeadroomPercent
		*out = new(int32)
		**out = **in
	}
	if in.NodeShare != nil {
		in, out := &in.NodeShare, &out.NodeShare
		*out = new(NodeShareSizing)
		(*in).DeepCopyInto(*out)
	}
	if in.MinRequests != nil {
		in, out := &in.MinRequests, &out.MinRequests
		*out = make(v1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	if in.MaxRequests != nil {
		in, out := &in.MaxRequests, &out.MaxRequests
		*out = make(v1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkerSizing.
func (in *WorkerSizing) DeepCopy() *WorkerSizing {
	if in == nil {
		return nil
	}
	out := new(WorkerSizing)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadIdentity) DeepCopyInto(out *WorkloadIdentity) {
	*out = *in
	in.Signer.DeepCopyInto(&out.Signer)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadIdentity.
func (in *WorkloadIdentity) DeepCopy() *WorkloadIdentity {
	if in == nil {
		return nil
	}
	out := new(WorkloadIdentity)
	in.DeepCopyInto(out)
	return out
}
