//go:build load

package load

import (
	"fmt"
	"runtime"
	"strings"
	"time"
)

// goroutineLeakSlack is the tolerance, in goroutines, for the post-teardown
// leak check — a handful of runtime/HTTP-client goroutines can linger briefly
// after Stop without indicating a listener leak.
const goroutineLeakSlack = 16

// SLO is one pass/fail acceptance criterion evaluated against a Result.
type SLO struct {
	Name string
	Want string
	Got  string
	Pass bool
}

// SLOs returns the acceptance criteria for the run. The headline criterion is
// sustained concurrency: the harness must hold ≥95% of the target virtual
// sessions throughout the steady window.
func (r *Result) SLOs() []SLO {
	target := r.Config.TargetSessions()
	wantSessions := 0.95 * float64(target)

	return []SLO{
		{
			Name: "sustained concurrent sessions",
			Want: fmt.Sprintf("avg ≥ %.0f (95%% of %d)", wantSessions, target),
			Got:  fmt.Sprintf("avg %.0f (min %d, max %d)", r.SessionsAvg, r.SessionsMin, r.SessionsMax),
			Pass: r.SessionsAvg >= wantSessions,
		},
		{
			Name: "re-registration per job ≈ 1 (Q114)",
			Want: "0.90 – 1.10",
			Got:  fmt.Sprintf("%.3f (%d recycles / %.0f jobs)", r.RecyclesPerJob, r.Recycles, r.JobsAcquired),
			Pass: r.RecyclesPerJob >= 0.90 && r.RecyclesPerJob <= 1.10,
		},
		{
			Name: "re-registration errors",
			Want: "0",
			Got:  fmt.Sprintf("%d", r.RecycleErrors),
			Pass: r.RecycleErrors == 0,
		},
		{
			Name: "throughput",
			Want: "> 0 jobs/s",
			Got:  fmt.Sprintf("%.0f jobs/s", r.Throughput),
			Pass: r.Throughput > 0,
		},
		{
			Name: "no goroutine leak after teardown",
			Want: fmt.Sprintf("≤ %d", goroutineLeakSlack),
			Got:  fmt.Sprintf("%d (baseline %d, peak %d)", r.LeakedGoroutines, r.BaselineGoroutines, r.PeakGoroutines),
			Pass: r.LeakedGoroutines <= goroutineLeakSlack,
		},
	}
}

// Passed reports whether every SLO passed.
func (r *Result) Passed() bool {
	for _, s := range r.SLOs() {
		if !s.Pass {
			return false
		}
	}
	return true
}

// Summary renders a compact multi-line summary for the test log.
func (r *Result) Summary() string {
	var b strings.Builder
	fmt.Fprintf(&b, "load result: %d tenants × %d listeners = %d target sessions\n",
		r.Config.Tenants, r.Config.ListenersPerTenant, r.Config.TargetSessions())
	fmt.Fprintf(&b, "  sustained sessions : avg %.0f (min %d / max %d)\n", r.SessionsAvg, r.SessionsMin, r.SessionsMax)
	fmt.Fprintf(&b, "  throughput         : %.0f jobs/s (%.0f jobs in steady window)\n", r.Throughput, r.JobsAcquired)
	fmt.Fprintf(&b, "  re-registration    : %.3f /job, p50 %s p95 %s p99 %s max %s\n",
		r.RecyclesPerJob, dur(r.RecycleP50), dur(r.RecycleP95), dur(r.RecycleP99), dur(r.RecycleMax))
	fmt.Fprintf(&b, "  goroutines         : peak %d, leaked %d (baseline %d)\n", r.PeakGoroutines, r.LeakedGoroutines, r.BaselineGoroutines)
	fmt.Fprintf(&b, "  memory             : heap-inuse %s, sys %s, %s/session\n",
		bytesH(r.HeapInuseBytes), bytesH(r.SysBytes), bytesHf(r.BytesPerSession))
	for _, s := range r.SLOs() {
		mark := "PASS"
		if !s.Pass {
			mark = "FAIL"
		}
		fmt.Fprintf(&b, "  [%s] %s — want %s, got %s\n", mark, s.Name, s.Want, s.Got)
	}
	return b.String()
}

// Markdown renders a committable report.
func (r *Result) Markdown(at time.Time) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# AGC load test — %s\n\n", at.UTC().Format(time.RFC3339))
	fmt.Fprintf(&b, "Generated by `cmd/agc/test/load` (in-process listener-core harness, Q13). ")
	fmt.Fprintf(&b, "See [README](../README.md) for what this does and does not measure.\n\n")

	fmt.Fprintf(&b, "## Host\n\n")
	fmt.Fprintf(&b, "| | |\n|---|---|\n")
	fmt.Fprintf(&b, "| Go | %s |\n", runtime.Version())
	fmt.Fprintf(&b, "| OS/arch | %s/%s |\n", runtime.GOOS, runtime.GOARCH)
	fmt.Fprintf(&b, "| NumCPU | %d |\n", runtime.NumCPU())
	fmt.Fprintf(&b, "| GOMAXPROCS | %d |\n\n", runtime.GOMAXPROCS(0))

	c := r.Config
	fmt.Fprintf(&b, "## Configuration\n\n")
	fmt.Fprintf(&b, "| Knob | Value |\n|---|---|\n")
	fmt.Fprintf(&b, "| tenants | %d |\n", c.Tenants)
	fmt.Fprintf(&b, "| listeners/tenant | %d |\n", c.ListenersPerTenant)
	fmt.Fprintf(&b, "| **target sessions** | **%d** |\n", c.TargetSessions())
	fmt.Fprintf(&b, "| job duration | %s |\n", c.JobDuration)
	fmt.Fprintf(&b, "| think time | %s |\n", c.ThinkTime)
	fmt.Fprintf(&b, "| warmup | %s |\n", c.Warmup)
	fmt.Fprintf(&b, "| steady window | %s |\n\n", c.Duration)

	fmt.Fprintf(&b, "## Results\n\n")
	fmt.Fprintf(&b, "| Metric | Value |\n|---|---|\n")
	fmt.Fprintf(&b, "| sustained sessions (avg) | %.0f |\n", r.SessionsAvg)
	fmt.Fprintf(&b, "| sustained sessions (min / max) | %d / %d |\n", r.SessionsMin, r.SessionsMax)
	fmt.Fprintf(&b, "| throughput | %.0f jobs/s |\n", r.Throughput)
	fmt.Fprintf(&b, "| jobs acquired (steady window) | %.0f |\n", r.JobsAcquired)
	fmt.Fprintf(&b, "| re-registrations / job (Q114) | %.3f |\n", r.RecyclesPerJob)
	fmt.Fprintf(&b, "| re-registration latency p50 / p95 / p99 / max | %s / %s / %s / %s |\n",
		dur(r.RecycleP50), dur(r.RecycleP95), dur(r.RecycleP99), dur(r.RecycleMax))
	fmt.Fprintf(&b, "| re-registration errors | %d |\n", r.RecycleErrors)
	fmt.Fprintf(&b, "| peak goroutines | %d |\n", r.PeakGoroutines)
	fmt.Fprintf(&b, "| leaked goroutines (post-teardown) | %d |\n", r.LeakedGoroutines)
	fmt.Fprintf(&b, "| peak heap-inuse | %s |\n", bytesH(r.HeapInuseBytes))
	fmt.Fprintf(&b, "| peak sys (OS-reserved) | %s |\n", bytesH(r.SysBytes))
	fmt.Fprintf(&b, "| memory / session (heap-inuse) | %s |\n\n", bytesHf(r.BytesPerSession))

	fmt.Fprintf(&b, "## SLOs\n\n")
	fmt.Fprintf(&b, "| Result | Criterion | Want | Got |\n|---|---|---|---|\n")
	for _, s := range r.SLOs() {
		mark := "✅"
		if !s.Pass {
			mark = "❌"
		}
		fmt.Fprintf(&b, "| %s | %s | %s | %s |\n", mark, s.Name, s.Want, s.Got)
	}
	verdict := "PASS"
	if !r.Passed() {
		verdict = "FAIL"
	}
	fmt.Fprintf(&b, "\n**Overall: %s**\n", verdict)
	return b.String()
}

func dur(d time.Duration) string {
	return d.Round(time.Microsecond).String()
}

func bytesH(n uint64) string { return bytesHf(float64(n)) }

func bytesHf(f float64) string {
	const unit = 1024.0
	switch {
	case f >= unit*unit*unit:
		return fmt.Sprintf("%.2f GiB", f/(unit*unit*unit))
	case f >= unit*unit:
		return fmt.Sprintf("%.2f MiB", f/(unit*unit))
	case f >= unit:
		return fmt.Sprintf("%.2f KiB", f/unit)
	default:
		return fmt.Sprintf("%.0f B", f)
	}
}
