on:
  pull_request:
  push:
    branches: [main]
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: run unit tests
        run: |
          GOWORK=off go test ./...
          (cd cmd/agc && go test ./...)
          (cd cmd/probe && go test ./...)
