{{- /*
Fork of crd-ref-docs' built-in markdown gvList template. A --templates-dir
replaces the whole built-in set, so all four templates live here even where the
only change is the page preamble below. Re-diff against
tools/vendor/github.com/elastic/crd-ref-docs/templates/markdown/ when the pinned
crd-ref-docs version moves.
*/ -}}
{{- define "gvList" -}}
{{- $groupVersions := . -}}
<!-- GENERATED by crd-ref-docs from the kubebuilder markers in api/v2beta1; regenerate with `make api-reference`. Do not edit by hand. -->
# API reference

Every field of every `actions-gateway.com/v2beta1` kind, generated from the Go
types the CRD schemas are generated from. For what the kinds are and how they fit
together, start at the [reference overview](README.md); for the deprecated
`v1alpha1` and `v2alpha1` versions, see [Deprecations & the v2.0.0
removal](../operations/v1alpha1-deprecation.md).

## Packages
{{- range $groupVersions }}
- {{ markdownRenderGVLink . }}
{{- end }}

{{ range $groupVersions }}
{{ template "gvDetails" . }}
{{ end }}

{{- end -}}
